# Generated by Django 3.0.4 on 2020-03-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertjetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Body', models.TextField()),
                ('Cover', models.ImageField(blank=True, upload_to='posts_images')),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
